package com.momnop.modularsonics.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import org.lwjgl.opengl.GL11;

/**
 * TenthSonic - Undefined
 * Created using Tabula 4.1.1
 */
public class ModelTenthSonic extends ModelBase {
    public ModelRenderer rubberGripBottom;
    public ModelRenderer rubberGrip;
    public ModelRenderer metalHandleBottom;
    public ModelRenderer metalHandleMiddle;
    public ModelRenderer metalHandleTop;
    public ModelRenderer stoneGripOne;
    public ModelRenderer stoneOutside1;
    public ModelRenderer stoneInside1;
    public ModelRenderer stoneOutside2;
    public ModelRenderer stoneInside2;
    public ModelRenderer stoneCasing;
    public ModelRenderer sliderPartA;
    public ModelRenderer sliderPartB;
    public ModelRenderer sliderPartC;
    public ModelRenderer blackPart;
    public ModelRenderer sideBarLeft;
    public ModelRenderer sideBarRight;
    public ModelRenderer bottomMetal;
    public ModelRenderer beforeMiddleMetal;
    public ModelRenderer middleMetal;
    public ModelRenderer topMetal;
    public ModelRenderer bottomLightMetal;
    public ModelRenderer lightCorner1;
    public ModelRenderer lightCorner2;
    public ModelRenderer lightCorner3;
    public ModelRenderer lightCorner4;
    public ModelRenderer lightRod;
    public ModelRenderer topLightMetal;
    public ModelRenderer topLight;

    public ModelTenthSonic() {
        this.textureWidth = 64;
        this.textureHeight = 32;
        this.sliderPartA = new ModelRenderer(this, 22, 27);
        this.sliderPartA.setRotationPoint(-1.0F, 11.1F, -1.57F);
        this.sliderPartA.addBox(0.0F, 0.0F, 0.0F, 1, 2, 1, 0.0F);
        this.setRotateAngle(sliderPartA, 0.0F, 0.3490658503988659F, 0.0F);
        this.sliderPartB = new ModelRenderer(this, 22, 27);
        this.sliderPartB.setRotationPoint(-0.5F, 11.1F, -1.6F);
        this.sliderPartB.addBox(0.0F, 0.0F, 0.0F, 1, 2, 1, 0.0F);
        this.blackPart = new ModelRenderer(this, 60, 22);
        this.blackPart.setRotationPoint(-0.2F, 3.7F, -1.52F);
        this.blackPart.addBox(0.0F, 0.0F, 0.0F, 1, 9, 1, 0.0F);
        this.lightCorner1 = new ModelRenderer(this, 36, 0);
        this.lightCorner1.setRotationPoint(-1.9F, -5.5F, -1.2F);
        this.lightCorner1.addBox(0.0F, 0.0F, 0.0F, 1, 5, 1, 0.0F);
        this.setRotateAngle(lightCorner1, 0.0F, 0.7853981633974483F, 0.0F);
        this.lightCorner3 = new ModelRenderer(this, 36, 0);
        this.lightCorner3.setRotationPoint(0.5F, -5.5F, 1.2F);
        this.lightCorner3.addBox(0.0F, 0.0F, 0.0F, 1, 5, 1, 0.0F);
        this.setRotateAngle(lightCorner3, 0.0F, 0.7853981633974483F, 0.0F);
        this.stoneInside2 = new ModelRenderer(this, 24, 28);
        this.stoneInside2.setRotationPoint(-1.35F, 11.8F, -1.35F);
        this.stoneInside2.addBox(0.0F, 0.0F, 0.0F, 3, 1, 3, 0.0F);
        this.topLightMetal = new ModelRenderer(this, 52, 0);
        this.topLightMetal.setRotationPoint(-1.5F, -5.5F, -1.5F);
        this.topLightMetal.addBox(0.0F, 0.0F, 0.0F, 3, 1, 3, 0.0F);
        this.stoneGripOne = new ModelRenderer(this, 12, 27);
        this.stoneGripOne.setRotationPoint(-1.36F, 14.0F, -1.36F);
        this.stoneGripOne.addBox(0.0F, 0.0F, 0.0F, 3, 2, 3, 0.0F);
        this.stoneCasing = new ModelRenderer(this, 36, 20);
        this.stoneCasing.setRotationPoint(-1.5F, 3.7F, -1.5F);
        this.stoneCasing.addBox(0.0F, 0.0F, 0.0F, 3, 9, 3, 0.0F);
        this.bottomLightMetal = new ModelRenderer(this, 52, 0);
        this.bottomLightMetal.setRotationPoint(-1.5F, -1.1F, -1.5F);
        this.bottomLightMetal.addBox(0.0F, 0.0F, 0.0F, 3, 1, 3, 0.0F);
        this.lightCorner4 = new ModelRenderer(this, 36, 0);
        this.lightCorner4.setRotationPoint(-1.9F, -5.5F, 1.2F);
        this.lightCorner4.addBox(0.0F, 0.0F, 0.0F, 1, 5, 1, 0.0F);
        this.setRotateAngle(lightCorner4, 0.0F, 0.7853981633974483F, 0.0F);
        this.stoneOutside1 = new ModelRenderer(this, 24, 28);
        this.stoneOutside1.setRotationPoint(-1.5F, 13.1F, -1.5F);
        this.stoneOutside1.addBox(0.0F, 0.0F, 0.0F, 3, 1, 3, 0.0F);
        this.metalHandleBottom = new ModelRenderer(this, 52, 0);
        this.metalHandleBottom.setRotationPoint(-1.35F, 17.6F, -1.35F);
        this.metalHandleBottom.addBox(0.0F, 0.0F, 0.0F, 3, 3, 3, 0.0F);
        this.stoneInside1 = new ModelRenderer(this, 24, 28);
        this.stoneInside1.setRotationPoint(-1.35F, 12.9F, -1.35F);
        this.stoneInside1.addBox(0.0F, 0.0F, 0.0F, 3, 1, 3, 0.0F);
        this.topMetal = new ModelRenderer(this, 52, 0);
        this.topMetal.setRotationPoint(-1.35F, 0.0F, -1.35F);
        this.topMetal.addBox(0.0F, 0.0F, 0.0F, 3, 1, 3, 0.0F);
        this.rubberGrip = new ModelRenderer(this, 0, 22);
        this.rubberGrip.setRotationPoint(-1.5F, 19.0F, -1.5F);
        this.rubberGrip.addBox(0.0F, 0.0F, 0.0F, 3, 4, 3, 0.0F);
        this.topLight = new ModelRenderer(this, 52, 18);
        this.topLight.setRotationPoint(-1.2F, -6.5F, -1.2F);
        this.topLight.addBox(0.0F, 0.0F, 0.0F, 3, 1, 3, 0.0F);
        this.lightCorner2 = new ModelRenderer(this, 36, 0);
        this.lightCorner2.setRotationPoint(0.5F, -5.5F, -1.2F);
        this.lightCorner2.addBox(0.0F, 0.0F, 0.0F, 1, 5, 1, 0.0F);
        this.setRotateAngle(lightCorner2, 0.0F, 0.7853981633974483F, 0.0F);
        this.middleMetal = new ModelRenderer(this, 52, 0);
        this.middleMetal.setRotationPoint(-1.05F, 0.9F, -1.05F);
        this.middleMetal.addBox(0.0F, 0.0F, 0.0F, 3, 1, 3, 0.0F);
        this.rubberGripBottom = new ModelRenderer(this, 0, 29);
        this.rubberGripBottom.setRotationPoint(-1.2F, 23.0F, -1.2F);
        this.rubberGripBottom.addBox(0.0F, 0.0F, 0.0F, 2, 1, 2, 0.0F);
        this.sideBarRight = new ModelRenderer(this, 56, 23);
        this.sideBarRight.setRotationPoint(1.42F, 4.9F, -0.14F);
        this.sideBarRight.addBox(0.0F, 0.0F, 0.0F, 1, 8, 1, 0.0F);
        this.sideBarLeft = new ModelRenderer(this, 56, 23);
        this.sideBarLeft.setRotationPoint(-1.52F, 4.9F, -0.14F);
        this.sideBarLeft.addBox(0.0F, 0.0F, 0.0F, 1, 8, 1, 0.0F);
        this.beforeMiddleMetal = new ModelRenderer(this, 52, 0);
        this.beforeMiddleMetal.setRotationPoint(-1.35F, 1.9F, -1.35F);
        this.beforeMiddleMetal.addBox(0.0F, 0.0F, 0.0F, 3, 2, 3, 0.0F);
        this.lightRod = new ModelRenderer(this, 36, 0);
        this.lightRod.setRotationPoint(-0.4F, -4.5F, -0.4F);
        this.lightRod.addBox(0.0F, 0.0F, 0.0F, 1, 4, 1, 0.0F);
        this.metalHandleMiddle = new ModelRenderer(this, 40, 0);
        this.metalHandleMiddle.setRotationPoint(-1.2F, 16.9F, -1.2F);
        this.metalHandleMiddle.addBox(0.0F, 0.0F, 0.0F, 3, 1, 3, 0.0F);
        this.metalHandleTop = new ModelRenderer(this, 40, 0);
        this.metalHandleTop.setRotationPoint(-1.35F, 15.9F, -1.35F);
        this.metalHandleTop.addBox(0.0F, 0.0F, 0.0F, 3, 1, 3, 0.0F);
        this.stoneOutside2 = new ModelRenderer(this, 24, 28);
        this.stoneOutside2.setRotationPoint(-1.5F, 12.0F, -1.5F);
        this.stoneOutside2.addBox(0.0F, 0.0F, 0.0F, 3, 1, 3, 0.0F);
        this.bottomMetal = new ModelRenderer(this, 52, 0);
        this.bottomMetal.setRotationPoint(-1.5F, 2.5F, -1.5F);
        this.bottomMetal.addBox(0.0F, 0.0F, 0.0F, 3, 2, 3, 0.0F);
        this.sliderPartC = new ModelRenderer(this, 22, 27);
        this.sliderPartC.setRotationPoint(0.5F, 11.1F, -1.6F);
        this.sliderPartC.addBox(0.0F, 0.0F, 0.0F, 1, 2, 1, 0.0F);
        this.setRotateAngle(sliderPartC, 0.0F, -0.3490658503988659F, 0.0F);
    }

    @Override
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) { 
        GL11.glPushMatrix();
        GL11.glTranslatef(this.sliderPartA.offsetX, this.sliderPartA.offsetY, this.sliderPartA.offsetZ);
        GL11.glTranslatef(this.sliderPartA.rotationPointX * f5, this.sliderPartA.rotationPointY * f5, this.sliderPartA.rotationPointZ * f5);
        GL11.glScaled(0.5D, 1.0D, 0.1D);
        GL11.glTranslatef(-this.sliderPartA.offsetX, -this.sliderPartA.offsetY, -this.sliderPartA.offsetZ);
        GL11.glTranslatef(-this.sliderPartA.rotationPointX * f5, -this.sliderPartA.rotationPointY * f5, -this.sliderPartA.rotationPointZ * f5);
        this.sliderPartA.render(f5);
        GL11.glPopMatrix();
        GL11.glPushMatrix();
        GL11.glTranslatef(this.sliderPartB.offsetX, this.sliderPartB.offsetY, this.sliderPartB.offsetZ);
        GL11.glTranslatef(this.sliderPartB.rotationPointX * f5, this.sliderPartB.rotationPointY * f5, this.sliderPartB.rotationPointZ * f5);
        GL11.glScaled(1.0D, 1.0D, 0.1D);
        GL11.glTranslatef(-this.sliderPartB.offsetX, -this.sliderPartB.offsetY, -this.sliderPartB.offsetZ);
        GL11.glTranslatef(-this.sliderPartB.rotationPointX * f5, -this.sliderPartB.rotationPointY * f5, -this.sliderPartB.rotationPointZ * f5);
        this.sliderPartB.render(f5);
        GL11.glPopMatrix();
        GL11.glPushMatrix();
        GL11.glTranslatef(this.blackPart.offsetX, this.blackPart.offsetY, this.blackPart.offsetZ);
        GL11.glTranslatef(this.blackPart.rotationPointX * f5, this.blackPart.rotationPointY * f5, this.blackPart.rotationPointZ * f5);
        GL11.glScaled(0.4D, 1.0D, 0.1D);
        GL11.glTranslatef(-this.blackPart.offsetX, -this.blackPart.offsetY, -this.blackPart.offsetZ);
        GL11.glTranslatef(-this.blackPart.rotationPointX * f5, -this.blackPart.rotationPointY * f5, -this.blackPart.rotationPointZ * f5);
        this.blackPart.render(f5);
        GL11.glPopMatrix();
        GL11.glPushMatrix();
        GL11.glTranslatef(this.lightCorner1.offsetX, this.lightCorner1.offsetY, this.lightCorner1.offsetZ);
        GL11.glTranslatef(this.lightCorner1.rotationPointX * f5, this.lightCorner1.rotationPointY * f5, this.lightCorner1.rotationPointZ * f5);
        GL11.glScaled(1.0D, 1.1D, 1.0D);
        GL11.glTranslatef(-this.lightCorner1.offsetX, -this.lightCorner1.offsetY, -this.lightCorner1.offsetZ);
        GL11.glTranslatef(-this.lightCorner1.rotationPointX * f5, -this.lightCorner1.rotationPointY * f5, -this.lightCorner1.rotationPointZ * f5);
        this.lightCorner1.render(f5);
        GL11.glPopMatrix();
        GL11.glPushMatrix();
        GL11.glTranslatef(this.lightCorner3.offsetX, this.lightCorner3.offsetY, this.lightCorner3.offsetZ);
        GL11.glTranslatef(this.lightCorner3.rotationPointX * f5, this.lightCorner3.rotationPointY * f5, this.lightCorner3.rotationPointZ * f5);
        GL11.glScaled(1.0D, 1.1D, 1.0D);
        GL11.glTranslatef(-this.lightCorner3.offsetX, -this.lightCorner3.offsetY, -this.lightCorner3.offsetZ);
        GL11.glTranslatef(-this.lightCorner3.rotationPointX * f5, -this.lightCorner3.rotationPointY * f5, -this.lightCorner3.rotationPointZ * f5);
        this.lightCorner3.render(f5);
        GL11.glPopMatrix();
        GL11.glPushMatrix();
        GL11.glTranslatef(this.stoneInside2.offsetX, this.stoneInside2.offsetY, this.stoneInside2.offsetZ);
        GL11.glTranslatef(this.stoneInside2.rotationPointX * f5, this.stoneInside2.rotationPointY * f5, this.stoneInside2.rotationPointZ * f5);
        GL11.glScaled(0.9D, 0.2D, 0.9D);
        GL11.glTranslatef(-this.stoneInside2.offsetX, -this.stoneInside2.offsetY, -this.stoneInside2.offsetZ);
        GL11.glTranslatef(-this.stoneInside2.rotationPointX * f5, -this.stoneInside2.rotationPointY * f5, -this.stoneInside2.rotationPointZ * f5);
        this.stoneInside2.render(f5);
        GL11.glPopMatrix();
        GL11.glPushMatrix();
        GL11.glTranslatef(this.topLightMetal.offsetX, this.topLightMetal.offsetY, this.topLightMetal.offsetZ);
        GL11.glTranslatef(this.topLightMetal.rotationPointX * f5, this.topLightMetal.rotationPointY * f5, this.topLightMetal.rotationPointZ * f5);
        GL11.glScaled(1.0D, 1.1D, 1.0D);
        GL11.glTranslatef(-this.topLightMetal.offsetX, -this.topLightMetal.offsetY, -this.topLightMetal.offsetZ);
        GL11.glTranslatef(-this.topLightMetal.rotationPointX * f5, -this.topLightMetal.rotationPointY * f5, -this.topLightMetal.rotationPointZ * f5);
        this.topLightMetal.render(f5);
        GL11.glPopMatrix();
        GL11.glPushMatrix();
        GL11.glTranslatef(this.stoneGripOne.offsetX, this.stoneGripOne.offsetY, this.stoneGripOne.offsetZ);
        GL11.glTranslatef(this.stoneGripOne.rotationPointX * f5, this.stoneGripOne.rotationPointY * f5, this.stoneGripOne.rotationPointZ * f5);
        GL11.glScaled(0.9D, 1.0D, 0.9D);
        GL11.glTranslatef(-this.stoneGripOne.offsetX, -this.stoneGripOne.offsetY, -this.stoneGripOne.offsetZ);
        GL11.glTranslatef(-this.stoneGripOne.rotationPointX * f5, -this.stoneGripOne.rotationPointY * f5, -this.stoneGripOne.rotationPointZ * f5);
        this.stoneGripOne.render(f5);
        GL11.glPopMatrix();
        GL11.glPushMatrix();
        GL11.glTranslatef(this.stoneCasing.offsetX, this.stoneCasing.offsetY, this.stoneCasing.offsetZ);
        GL11.glTranslatef(this.stoneCasing.rotationPointX * f5, this.stoneCasing.rotationPointY * f5, this.stoneCasing.rotationPointZ * f5);
        GL11.glScaled(1.0D, 0.9D, 1.0D);
        GL11.glTranslatef(-this.stoneCasing.offsetX, -this.stoneCasing.offsetY, -this.stoneCasing.offsetZ);
        GL11.glTranslatef(-this.stoneCasing.rotationPointX * f5, -this.stoneCasing.rotationPointY * f5, -this.stoneCasing.rotationPointZ * f5);
        this.stoneCasing.render(f5);
        GL11.glPopMatrix();
        GL11.glPushMatrix();
        GL11.glTranslatef(this.bottomLightMetal.offsetX, this.bottomLightMetal.offsetY, this.bottomLightMetal.offsetZ);
        GL11.glTranslatef(this.bottomLightMetal.rotationPointX * f5, this.bottomLightMetal.rotationPointY * f5, this.bottomLightMetal.rotationPointZ * f5);
        GL11.glScaled(1.0D, 1.1D, 1.0D);
        GL11.glTranslatef(-this.bottomLightMetal.offsetX, -this.bottomLightMetal.offsetY, -this.bottomLightMetal.offsetZ);
        GL11.glTranslatef(-this.bottomLightMetal.rotationPointX * f5, -this.bottomLightMetal.rotationPointY * f5, -this.bottomLightMetal.rotationPointZ * f5);
        this.bottomLightMetal.render(f5);
        GL11.glPopMatrix();
        GL11.glPushMatrix();
        GL11.glTranslatef(this.lightCorner4.offsetX, this.lightCorner4.offsetY, this.lightCorner4.offsetZ);
        GL11.glTranslatef(this.lightCorner4.rotationPointX * f5, this.lightCorner4.rotationPointY * f5, this.lightCorner4.rotationPointZ * f5);
        GL11.glScaled(1.0D, 1.1D, 1.0D);
        GL11.glTranslatef(-this.lightCorner4.offsetX, -this.lightCorner4.offsetY, -this.lightCorner4.offsetZ);
        GL11.glTranslatef(-this.lightCorner4.rotationPointX * f5, -this.lightCorner4.rotationPointY * f5, -this.lightCorner4.rotationPointZ * f5);
        this.lightCorner4.render(f5);
        GL11.glPopMatrix();
        GL11.glPushMatrix();
        GL11.glTranslatef(this.stoneOutside1.offsetX, this.stoneOutside1.offsetY, this.stoneOutside1.offsetZ);
        GL11.glTranslatef(this.stoneOutside1.rotationPointX * f5, this.stoneOutside1.rotationPointY * f5, this.stoneOutside1.rotationPointZ * f5);
        GL11.glScaled(1.0D, 0.9D, 1.0D);
        GL11.glTranslatef(-this.stoneOutside1.offsetX, -this.stoneOutside1.offsetY, -this.stoneOutside1.offsetZ);
        GL11.glTranslatef(-this.stoneOutside1.rotationPointX * f5, -this.stoneOutside1.rotationPointY * f5, -this.stoneOutside1.rotationPointZ * f5);
        this.stoneOutside1.render(f5);
        GL11.glPopMatrix();
        GL11.glPushMatrix();
        GL11.glTranslatef(this.metalHandleBottom.offsetX, this.metalHandleBottom.offsetY, this.metalHandleBottom.offsetZ);
        GL11.glTranslatef(this.metalHandleBottom.rotationPointX * f5, this.metalHandleBottom.rotationPointY * f5, this.metalHandleBottom.rotationPointZ * f5);
        GL11.glScaled(0.9D, 1.0D, 0.9D);
        GL11.glTranslatef(-this.metalHandleBottom.offsetX, -this.metalHandleBottom.offsetY, -this.metalHandleBottom.offsetZ);
        GL11.glTranslatef(-this.metalHandleBottom.rotationPointX * f5, -this.metalHandleBottom.rotationPointY * f5, -this.metalHandleBottom.rotationPointZ * f5);
        this.metalHandleBottom.render(f5);
        GL11.glPopMatrix();
        GL11.glPushMatrix();
        GL11.glTranslatef(this.stoneInside1.offsetX, this.stoneInside1.offsetY, this.stoneInside1.offsetZ);
        GL11.glTranslatef(this.stoneInside1.rotationPointX * f5, this.stoneInside1.rotationPointY * f5, this.stoneInside1.rotationPointZ * f5);
        GL11.glScaled(0.9D, 0.2D, 0.9D);
        GL11.glTranslatef(-this.stoneInside1.offsetX, -this.stoneInside1.offsetY, -this.stoneInside1.offsetZ);
        GL11.glTranslatef(-this.stoneInside1.rotationPointX * f5, -this.stoneInside1.rotationPointY * f5, -this.stoneInside1.rotationPointZ * f5);
        this.stoneInside1.render(f5);
        GL11.glPopMatrix();
        GL11.glPushMatrix();
        GL11.glTranslatef(this.topMetal.offsetX, this.topMetal.offsetY, this.topMetal.offsetZ);
        GL11.glTranslatef(this.topMetal.rotationPointX * f5, this.topMetal.rotationPointY * f5, this.topMetal.rotationPointZ * f5);
        GL11.glScaled(0.9D, 0.9D, 0.9D);
        GL11.glTranslatef(-this.topMetal.offsetX, -this.topMetal.offsetY, -this.topMetal.offsetZ);
        GL11.glTranslatef(-this.topMetal.rotationPointX * f5, -this.topMetal.rotationPointY * f5, -this.topMetal.rotationPointZ * f5);
        this.topMetal.render(f5);
        GL11.glPopMatrix();
        this.rubberGrip.render(f5);
        GL11.glPushMatrix();
        GL11.glTranslatef(this.topLight.offsetX, this.topLight.offsetY, this.topLight.offsetZ);
        GL11.glTranslatef(this.topLight.rotationPointX * f5, this.topLight.rotationPointY * f5, this.topLight.rotationPointZ * f5);
        GL11.glScaled(0.8D, 1.1D, 0.8D);
        GL11.glTranslatef(-this.topLight.offsetX, -this.topLight.offsetY, -this.topLight.offsetZ);
        GL11.glTranslatef(-this.topLight.rotationPointX * f5, -this.topLight.rotationPointY * f5, -this.topLight.rotationPointZ * f5);
        this.topLight.render(f5);
        GL11.glPopMatrix();
        GL11.glPushMatrix();
        GL11.glTranslatef(this.lightCorner2.offsetX, this.lightCorner2.offsetY, this.lightCorner2.offsetZ);
        GL11.glTranslatef(this.lightCorner2.rotationPointX * f5, this.lightCorner2.rotationPointY * f5, this.lightCorner2.rotationPointZ * f5);
        GL11.glScaled(1.0D, 1.1D, 1.0D);
        GL11.glTranslatef(-this.lightCorner2.offsetX, -this.lightCorner2.offsetY, -this.lightCorner2.offsetZ);
        GL11.glTranslatef(-this.lightCorner2.rotationPointX * f5, -this.lightCorner2.rotationPointY * f5, -this.lightCorner2.rotationPointZ * f5);
        this.lightCorner2.render(f5);
        GL11.glPopMatrix();
        GL11.glPushMatrix();
        GL11.glTranslatef(this.middleMetal.offsetX, this.middleMetal.offsetY, this.middleMetal.offsetZ);
        GL11.glTranslatef(this.middleMetal.rotationPointX * f5, this.middleMetal.rotationPointY * f5, this.middleMetal.rotationPointZ * f5);
        GL11.glScaled(0.7D, 1.0D, 0.7D);
        GL11.glTranslatef(-this.middleMetal.offsetX, -this.middleMetal.offsetY, -this.middleMetal.offsetZ);
        GL11.glTranslatef(-this.middleMetal.rotationPointX * f5, -this.middleMetal.rotationPointY * f5, -this.middleMetal.rotationPointZ * f5);
        this.middleMetal.render(f5);
        GL11.glPopMatrix();
        GL11.glPushMatrix();
        GL11.glTranslatef(this.rubberGripBottom.offsetX, this.rubberGripBottom.offsetY, this.rubberGripBottom.offsetZ);
        GL11.glTranslatef(this.rubberGripBottom.rotationPointX * f5, this.rubberGripBottom.rotationPointY * f5, this.rubberGripBottom.rotationPointZ * f5);
        GL11.glScaled(1.2D, 1.0D, 1.2D);
        GL11.glTranslatef(-this.rubberGripBottom.offsetX, -this.rubberGripBottom.offsetY, -this.rubberGripBottom.offsetZ);
        GL11.glTranslatef(-this.rubberGripBottom.rotationPointX * f5, -this.rubberGripBottom.rotationPointY * f5, -this.rubberGripBottom.rotationPointZ * f5);
        this.rubberGripBottom.render(f5);
        GL11.glPopMatrix();
        GL11.glPushMatrix();
        GL11.glTranslatef(this.sideBarRight.offsetX, this.sideBarRight.offsetY, this.sideBarRight.offsetZ);
        GL11.glTranslatef(this.sideBarRight.rotationPointX * f5, this.sideBarRight.rotationPointY * f5, this.sideBarRight.rotationPointZ * f5);
        GL11.glScaled(0.1D, 0.8D, 0.3D);
        GL11.glTranslatef(-this.sideBarRight.offsetX, -this.sideBarRight.offsetY, -this.sideBarRight.offsetZ);
        GL11.glTranslatef(-this.sideBarRight.rotationPointX * f5, -this.sideBarRight.rotationPointY * f5, -this.sideBarRight.rotationPointZ * f5);
        this.sideBarRight.render(f5);
        GL11.glPopMatrix();
        GL11.glPushMatrix();
        GL11.glTranslatef(this.sideBarLeft.offsetX, this.sideBarLeft.offsetY, this.sideBarLeft.offsetZ);
        GL11.glTranslatef(this.sideBarLeft.rotationPointX * f5, this.sideBarLeft.rotationPointY * f5, this.sideBarLeft.rotationPointZ * f5);
        GL11.glScaled(0.1D, 0.8D, 0.3D);
        GL11.glTranslatef(-this.sideBarLeft.offsetX, -this.sideBarLeft.offsetY, -this.sideBarLeft.offsetZ);
        GL11.glTranslatef(-this.sideBarLeft.rotationPointX * f5, -this.sideBarLeft.rotationPointY * f5, -this.sideBarLeft.rotationPointZ * f5);
        this.sideBarLeft.render(f5);
        GL11.glPopMatrix();
        GL11.glPushMatrix();
        GL11.glTranslatef(this.beforeMiddleMetal.offsetX, this.beforeMiddleMetal.offsetY, this.beforeMiddleMetal.offsetZ);
        GL11.glTranslatef(this.beforeMiddleMetal.rotationPointX * f5, this.beforeMiddleMetal.rotationPointY * f5, this.beforeMiddleMetal.rotationPointZ * f5);
        GL11.glScaled(0.9D, 0.3D, 0.9D);
        GL11.glTranslatef(-this.beforeMiddleMetal.offsetX, -this.beforeMiddleMetal.offsetY, -this.beforeMiddleMetal.offsetZ);
        GL11.glTranslatef(-this.beforeMiddleMetal.rotationPointX * f5, -this.beforeMiddleMetal.rotationPointY * f5, -this.beforeMiddleMetal.rotationPointZ * f5);
        this.beforeMiddleMetal.render(f5);
        GL11.glPopMatrix();
        GL11.glPushMatrix();
        GL11.glTranslatef(this.lightRod.offsetX, this.lightRod.offsetY, this.lightRod.offsetZ);
        GL11.glTranslatef(this.lightRod.rotationPointX * f5, this.lightRod.rotationPointY * f5, this.lightRod.rotationPointZ * f5);
        GL11.glScaled(0.8D, 1.1D, 0.8D);
        GL11.glTranslatef(-this.lightRod.offsetX, -this.lightRod.offsetY, -this.lightRod.offsetZ);
        GL11.glTranslatef(-this.lightRod.rotationPointX * f5, -this.lightRod.rotationPointY * f5, -this.lightRod.rotationPointZ * f5);
        this.lightRod.render(f5);
        GL11.glPopMatrix();
        GL11.glPushMatrix();
        GL11.glTranslatef(this.metalHandleMiddle.offsetX, this.metalHandleMiddle.offsetY, this.metalHandleMiddle.offsetZ);
        GL11.glTranslatef(this.metalHandleMiddle.rotationPointX * f5, this.metalHandleMiddle.rotationPointY * f5, this.metalHandleMiddle.rotationPointZ * f5);
        GL11.glScaled(0.8D, 0.7D, 0.8D);
        GL11.glTranslatef(-this.metalHandleMiddle.offsetX, -this.metalHandleMiddle.offsetY, -this.metalHandleMiddle.offsetZ);
        GL11.glTranslatef(-this.metalHandleMiddle.rotationPointX * f5, -this.metalHandleMiddle.rotationPointY * f5, -this.metalHandleMiddle.rotationPointZ * f5);
        this.metalHandleMiddle.render(f5);
        GL11.glPopMatrix();
        GL11.glPushMatrix();
        GL11.glTranslatef(this.metalHandleTop.offsetX, this.metalHandleTop.offsetY, this.metalHandleTop.offsetZ);
        GL11.glTranslatef(this.metalHandleTop.rotationPointX * f5, this.metalHandleTop.rotationPointY * f5, this.metalHandleTop.rotationPointZ * f5);
        GL11.glScaled(0.9D, 1.0D, 0.9D);
        GL11.glTranslatef(-this.metalHandleTop.offsetX, -this.metalHandleTop.offsetY, -this.metalHandleTop.offsetZ);
        GL11.glTranslatef(-this.metalHandleTop.rotationPointX * f5, -this.metalHandleTop.rotationPointY * f5, -this.metalHandleTop.rotationPointZ * f5);
        this.metalHandleTop.render(f5);
        GL11.glPopMatrix();
        GL11.glPushMatrix();
        GL11.glTranslatef(this.stoneOutside2.offsetX, this.stoneOutside2.offsetY, this.stoneOutside2.offsetZ);
        GL11.glTranslatef(this.stoneOutside2.rotationPointX * f5, this.stoneOutside2.rotationPointY * f5, this.stoneOutside2.rotationPointZ * f5);
        GL11.glScaled(1.0D, 0.9D, 1.0D);
        GL11.glTranslatef(-this.stoneOutside2.offsetX, -this.stoneOutside2.offsetY, -this.stoneOutside2.offsetZ);
        GL11.glTranslatef(-this.stoneOutside2.rotationPointX * f5, -this.stoneOutside2.rotationPointY * f5, -this.stoneOutside2.rotationPointZ * f5);
        this.stoneOutside2.render(f5);
        GL11.glPopMatrix();
        GL11.glPushMatrix();
        GL11.glTranslatef(this.bottomMetal.offsetX, this.bottomMetal.offsetY, this.bottomMetal.offsetZ);
        GL11.glTranslatef(this.bottomMetal.rotationPointX * f5, this.bottomMetal.rotationPointY * f5, this.bottomMetal.rotationPointZ * f5);
        GL11.glScaled(1.0D, 0.6D, 1.0D);
        GL11.glTranslatef(-this.bottomMetal.offsetX, -this.bottomMetal.offsetY, -this.bottomMetal.offsetZ);
        GL11.glTranslatef(-this.bottomMetal.rotationPointX * f5, -this.bottomMetal.rotationPointY * f5, -this.bottomMetal.rotationPointZ * f5);
        this.bottomMetal.render(f5);
        GL11.glPopMatrix();
        GL11.glPushMatrix();
        GL11.glTranslatef(this.sliderPartC.offsetX, this.sliderPartC.offsetY, this.sliderPartC.offsetZ);
        GL11.glTranslatef(this.sliderPartC.rotationPointX * f5, this.sliderPartC.rotationPointY * f5, this.sliderPartC.rotationPointZ * f5);
        GL11.glScaled(0.5D, 1.0D, 0.1D);
        GL11.glTranslatef(-this.sliderPartC.offsetX, -this.sliderPartC.offsetY, -this.sliderPartC.offsetZ);
        GL11.glTranslatef(-this.sliderPartC.rotationPointX * f5, -this.sliderPartC.rotationPointY * f5, -this.sliderPartC.rotationPointZ * f5);
        this.sliderPartC.render(f5);
        GL11.glPopMatrix();
    }

    /**
     * This is a helper function from Tabula to set the rotation of model parts
     */
    public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
        modelRenderer.rotateAngleX = x;
        modelRenderer.rotateAngleY = y;
        modelRenderer.rotateAngleZ = z;
    }
}
