package com.momnop.modularsonics.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import org.lwjgl.opengl.GL11;

/**
 * TenthSonic - Zundrel
 * Created using Tabula 4.1.1
 */
public class ModelTenthSonicOld extends ModelBase {
    public ModelRenderer SonicBase;
    public ModelRenderer SonicBase2;
    public ModelRenderer SonicBase3A;
    public ModelRenderer SonicBase4;
    public ModelRenderer SonicBase5;
    public ModelRenderer SonicBase6;
    public ModelRenderer SonicBase7;
    public ModelRenderer SonicBase8;
    public ModelRenderer SonicBase8_1;
    public ModelRenderer Hollow;
    public ModelRenderer Slider1;
    public ModelRenderer Slider2;
    public ModelRenderer TopConnector;
    public ModelRenderer Side1A;
    public ModelRenderer Side2A;
    public ModelRenderer MiddleSonicBase;
    public ModelRenderer SonicTop;
    public ModelRenderer SonicCorner1;
    public ModelRenderer SonicCorner2;
    public ModelRenderer SonicCorner3;
    public ModelRenderer SonicCorner4;
    public ModelRenderer SonicTop2;
    public ModelRenderer SonicLight2;
    public ModelRenderer SideBar1;
    public ModelRenderer SideBar2;
    public ModelRenderer TopRod;
    public ModelRenderer SonicBase3B;
    public ModelRenderer Side1B;
    public ModelRenderer Side2B;

    public ModelTenthSonicOld() {
        this.textureWidth = 64;
        this.textureHeight = 32;
        this.SonicBase4 = new ModelRenderer(this, 33, 0);
        this.SonicBase4.setRotationPoint(-1.5F, 16.0F, -1.5F);
        this.SonicBase4.addBox(0.0F, 0.0F, 0.0F, 3, 2, 3, 0.0F);
        this.Side2A = new ModelRenderer(this, 20, 4);
        this.Side2A.setRotationPoint(1.6F, 7.0F, -0.35F);
        this.Side2A.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
        this.SonicCorner3 = new ModelRenderer(this, 0, 19);
        this.SonicCorner3.setRotationPoint(0.6F, -1.0F, 1.35F);
        this.SonicCorner3.addBox(0.0F, 0.0F, 0.0F, 1, 5, 1, 0.0F);
        this.setRotateAngle(SonicCorner3, 0.0F, 0.7853981633974483F, 0.0F);
        this.SonicLight2 = new ModelRenderer(this, 0, 0);
        this.SonicLight2.setRotationPoint(-1.35F, -2.41F, -1.35F);
        this.SonicLight2.addBox(0.0F, 0.0F, 0.0F, 3, 2, 3, 0.0F);
        this.SideBar2 = new ModelRenderer(this, 4, 19);
        this.SideBar2.setRotationPoint(1.56F, 7.3F, -0.24F);
        this.SideBar2.addBox(0.0F, 0.0F, 0.0F, 1, 6, 1, 0.0F);
        this.SonicCorner4 = new ModelRenderer(this, 0, 19);
        this.SonicCorner4.setRotationPoint(-2.05F, -1.0F, 1.35F);
        this.SonicCorner4.addBox(0.0F, 0.0F, 0.0F, 1, 5, 1, 0.0F);
        this.setRotateAngle(SonicCorner4, 0.0F, 0.7853981633974483F, 0.0F);
        this.SonicTop = new ModelRenderer(this, 32, 6);
        this.SonicTop.setRotationPoint(-1.65F, 2.9F, -1.6F);
        this.SonicTop.addBox(0.0F, 0.0F, 0.0F, 3, 3, 3, 0.0F);
        this.Hollow = new ModelRenderer(this, 0, 25);
        this.Hollow.setRotationPoint(-0.2F, 7.0F, -1.61F);
        this.Hollow.addBox(0.0F, 0.0F, 0.0F, 1, 6, 1, 0.0F);
        this.SonicBase = new ModelRenderer(this, 56, 0);
        this.SonicBase.setRotationPoint(-1.0F, 23.0F, -1.0F);
        this.SonicBase.addBox(0.0F, 0.0F, 0.0F, 2, 1, 2, 0.0F);
        this.SonicCorner2 = new ModelRenderer(this, 0, 19);
        this.SonicCorner2.setRotationPoint(0.6F, -1.0F, -1.35F);
        this.SonicCorner2.addBox(0.0F, 0.0F, 0.0F, 1, 5, 1, 0.0F);
        this.setRotateAngle(SonicCorner2, 0.0F, 0.7853981633974483F, 0.0F);
        this.SonicBase6 = new ModelRenderer(this, 15, 0);
        this.SonicBase6.setRotationPoint(-1.5F, 15.0F, -1.5F);
        this.SonicBase6.addBox(0.0F, 0.0F, 0.0F, 3, 1, 3, 0.0F);
        this.Side2B = new ModelRenderer(this, 20, 4);
        this.Side2B.setRotationPoint(0.0F, 7.0F, 0.0F);
        this.Side2B.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
        this.SonicBase5 = new ModelRenderer(this, 15, 0);
        this.SonicBase5.setRotationPoint(-1.6F, 15.5F, -1.6F);
        this.SonicBase5.addBox(0.0F, 0.0F, 0.0F, 3, 1, 3, 0.0F);
        this.Slider2 = new ModelRenderer(this, 14, 0);
        this.Slider2.setRotationPoint(-0.5F, 11.54F, -1.6F);
        this.Slider2.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
        this.setRotateAngle(Slider2, -1.1383037381507017F, 0.0F, 0.0F);
        this.Side1A = new ModelRenderer(this, 20, 4);
        this.Side1A.setRotationPoint(-1.9F, 7.0F, -0.35F);
        this.Side1A.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
        this.SonicBase8 = new ModelRenderer(this, 15, 0);
        this.SonicBase8.setRotationPoint(-1.5F, 14.0F, -1.5F);
        this.SonicBase8.addBox(0.0F, 0.0F, 0.0F, 3, 1, 3, 0.0F);
        this.TopRod = new ModelRenderer(this, 0, 19);
        this.TopRod.setRotationPoint(-0.4F, -1.0F, -0.4F);
        this.TopRod.addBox(0.0F, 0.0F, 0.0F, 1, 5, 1, 0.0F);
        this.SonicBase3A = new ModelRenderer(this, 42, 10);
        this.SonicBase3A.setRotationPoint(-1.3F, 18.0F, -1.3F);
        this.SonicBase3A.addBox(0.0F, 0.0F, 0.0F, 2, 1, 2, 0.0F);
        this.SonicTop2 = new ModelRenderer(this, 0, 15);
        this.SonicTop2.setRotationPoint(-1.6F, -1.01F, -1.6F);
        this.SonicTop2.addBox(0.0F, 0.0F, 0.0F, 3, 1, 3, 0.0F);
        this.Side1B = new ModelRenderer(this, 20, 4);
        this.Side1B.setRotationPoint(0.0F, 7.0F, 0.0F);
        this.Side1B.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
        this.SonicBase7 = new ModelRenderer(this, 15, 0);
        this.SonicBase7.setRotationPoint(-1.6F, 14.5F, -1.6F);
        this.SonicBase7.addBox(0.0F, 0.0F, 0.0F, 3, 1, 3, 0.0F);
        this.SonicBase3B = new ModelRenderer(this, 42, 10);
        this.SonicBase3B.setRotationPoint(0.0F, 1.9F, 0.0F);
        this.SonicBase3B.addBox(0.0F, 0.0F, 0.0F, 2, 3, 2, 0.0F);
        this.Slider1 = new ModelRenderer(this, 14, 0);
        this.Slider1.setRotationPoint(-0.5F, 11.8F, -2.5F);
        this.Slider1.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
        this.SonicCorner1 = new ModelRenderer(this, 0, 19);
        this.SonicCorner1.setRotationPoint(-2.1F, -1.0F, -1.35F);
        this.SonicCorner1.addBox(0.0F, 0.0F, 0.0F, 1, 5, 1, 0.0F);
        this.setRotateAngle(SonicCorner1, 0.0F, 0.7853981633974483F, 0.0F);
        this.SonicBase8_1 = new ModelRenderer(this, 52, 6);
        this.SonicBase8_1.setRotationPoint(-1.7F, 6.0F, -1.6F);
        this.SonicBase8_1.addBox(0.0F, 0.0F, 0.0F, 3, 8, 3, 0.0F);
        this.TopConnector = new ModelRenderer(this, 41, 5);
        this.TopConnector.setRotationPoint(0.3F, 5.0F, 0.4F);
        this.TopConnector.addBox(-1.25F, 0.0F, -1.25F, 2, 1, 2, 0.0F);
        this.SonicBase2 = new ModelRenderer(this, 47, 0);
        this.SonicBase2.setRotationPoint(-1.5F, 20.0F, -1.5F);
        this.SonicBase2.addBox(0.0F, 0.0F, 0.0F, 3, 3, 3, 0.0F);
        this.MiddleSonicBase = new ModelRenderer(this, 42, 0);
        this.MiddleSonicBase.setRotationPoint(0.25F, 18.7F, 0.25F);
        this.MiddleSonicBase.addBox(-1.25F, 0.0F, -1.25F, 2, 1, 2, 0.0F);
        this.SideBar1 = new ModelRenderer(this, 4, 19);
        this.SideBar1.setRotationPoint(-1.74F, 7.3F, -0.24F);
        this.SideBar1.addBox(0.0F, 0.0F, 0.0F, 1, 6, 1, 0.0F);
        this.Side2A.addChild(this.Side2B);
        this.Side1A.addChild(this.Side1B);
        this.SonicBase3A.addChild(this.SonicBase3B);
    }

    @Override
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) { 
        this.SonicBase4.render(f5);
        GL11.glPushMatrix();
        GL11.glTranslatef(this.Side2A.offsetX, this.Side2A.offsetY, this.Side2A.offsetZ);
        GL11.glTranslatef(this.Side2A.rotationPointX * f5, this.Side2A.rotationPointY * f5, this.Side2A.rotationPointZ * f5);
        GL11.glScaled(0.2D, 0.7D, 0.7D);
        GL11.glTranslatef(-this.Side2A.offsetX, -this.Side2A.offsetY, -this.Side2A.offsetZ);
        GL11.glTranslatef(-this.Side2A.rotationPointX * f5, -this.Side2A.rotationPointY * f5, -this.Side2A.rotationPointZ * f5);
        this.Side2A.render(f5);
        GL11.glPopMatrix();
        this.SonicCorner3.render(f5);
        GL11.glPushMatrix();
        GL11.glTranslatef(this.SonicLight2.offsetX, this.SonicLight2.offsetY, this.SonicLight2.offsetZ);
        GL11.glTranslatef(this.SonicLight2.rotationPointX * f5, this.SonicLight2.rotationPointY * f5, this.SonicLight2.rotationPointZ * f5);
        GL11.glScaled(0.92D, 0.7D, 0.92D);
        GL11.glTranslatef(-this.SonicLight2.offsetX, -this.SonicLight2.offsetY, -this.SonicLight2.offsetZ);
        GL11.glTranslatef(-this.SonicLight2.rotationPointX * f5, -this.SonicLight2.rotationPointY * f5, -this.SonicLight2.rotationPointZ * f5);
        this.SonicLight2.render(f5);
        GL11.glPopMatrix();
        GL11.glPushMatrix();
        GL11.glTranslatef(this.SideBar2.offsetX, this.SideBar2.offsetY, this.SideBar2.offsetZ);
        GL11.glTranslatef(this.SideBar2.rotationPointX * f5, this.SideBar2.rotationPointY * f5, this.SideBar2.rotationPointZ * f5);
        GL11.glScaled(0.1D, 0.8D, 0.5D);
        GL11.glTranslatef(-this.SideBar2.offsetX, -this.SideBar2.offsetY, -this.SideBar2.offsetZ);
        GL11.glTranslatef(-this.SideBar2.rotationPointX * f5, -this.SideBar2.rotationPointY * f5, -this.SideBar2.rotationPointZ * f5);
        this.SideBar2.render(f5);
        GL11.glPopMatrix();
        this.SonicCorner4.render(f5);
        GL11.glPushMatrix();
        GL11.glTranslatef(this.SonicTop.offsetX, this.SonicTop.offsetY, this.SonicTop.offsetZ);
        GL11.glTranslatef(this.SonicTop.rotationPointX * f5, this.SonicTop.rotationPointY * f5, this.SonicTop.rotationPointZ * f5);
        GL11.glScaled(1.08D, 0.7D, 1.08D);
        GL11.glTranslatef(-this.SonicTop.offsetX, -this.SonicTop.offsetY, -this.SonicTop.offsetZ);
        GL11.glTranslatef(-this.SonicTop.rotationPointX * f5, -this.SonicTop.rotationPointY * f5, -this.SonicTop.rotationPointZ * f5);
        this.SonicTop.render(f5);
        GL11.glPopMatrix();
        GL11.glPushMatrix();
        GL11.glTranslatef(this.Hollow.offsetX, this.Hollow.offsetY, this.Hollow.offsetZ);
        GL11.glTranslatef(this.Hollow.rotationPointX * f5, this.Hollow.rotationPointY * f5, this.Hollow.rotationPointZ * f5);
        GL11.glScaled(0.5D, 0.9D, 0.06D);
        GL11.glTranslatef(-this.Hollow.offsetX, -this.Hollow.offsetY, -this.Hollow.offsetZ);
        GL11.glTranslatef(-this.Hollow.rotationPointX * f5, -this.Hollow.rotationPointY * f5, -this.Hollow.rotationPointZ * f5);
        this.Hollow.render(f5);
        GL11.glPopMatrix();
        this.SonicBase.render(f5);
        this.SonicCorner2.render(f5);
        GL11.glPushMatrix();
        GL11.glTranslatef(this.SonicBase6.offsetX, this.SonicBase6.offsetY, this.SonicBase6.offsetZ);
        GL11.glTranslatef(this.SonicBase6.rotationPointX * f5, this.SonicBase6.rotationPointY * f5, this.SonicBase6.rotationPointZ * f5);
        GL11.glScaled(1.0D, 0.5D, 1.0D);
        GL11.glTranslatef(-this.SonicBase6.offsetX, -this.SonicBase6.offsetY, -this.SonicBase6.offsetZ);
        GL11.glTranslatef(-this.SonicBase6.rotationPointX * f5, -this.SonicBase6.rotationPointY * f5, -this.SonicBase6.rotationPointZ * f5);
        this.SonicBase6.render(f5);
        GL11.glPopMatrix();
        GL11.glPushMatrix();
        GL11.glTranslatef(this.SonicBase5.offsetX, this.SonicBase5.offsetY, this.SonicBase5.offsetZ);
        GL11.glTranslatef(this.SonicBase5.rotationPointX * f5, this.SonicBase5.rotationPointY * f5, this.SonicBase5.rotationPointZ * f5);
        GL11.glScaled(1.1D, 0.5D, 1.1D);
        GL11.glTranslatef(-this.SonicBase5.offsetX, -this.SonicBase5.offsetY, -this.SonicBase5.offsetZ);
        GL11.glTranslatef(-this.SonicBase5.rotationPointX * f5, -this.SonicBase5.rotationPointY * f5, -this.SonicBase5.rotationPointZ * f5);
        this.SonicBase5.render(f5);
        GL11.glPopMatrix();
        GL11.glPushMatrix();
        GL11.glTranslatef(this.Slider2.offsetX, this.Slider2.offsetY, this.Slider2.offsetZ);
        GL11.glTranslatef(this.Slider2.rotationPointX * f5, this.Slider2.rotationPointY * f5, this.Slider2.rotationPointZ * f5);
        GL11.glScaled(1.1D, 0.6D, 1.0D);
        GL11.glTranslatef(-this.Slider2.offsetX, -this.Slider2.offsetY, -this.Slider2.offsetZ);
        GL11.glTranslatef(-this.Slider2.rotationPointX * f5, -this.Slider2.rotationPointY * f5, -this.Slider2.rotationPointZ * f5);
        this.Slider2.render(f5);
        GL11.glPopMatrix();
        GL11.glPushMatrix();
        GL11.glTranslatef(this.Side1A.offsetX, this.Side1A.offsetY, this.Side1A.offsetZ);
        GL11.glTranslatef(this.Side1A.rotationPointX * f5, this.Side1A.rotationPointY * f5, this.Side1A.rotationPointZ * f5);
        GL11.glScaled(0.2D, 0.7D, 0.7D);
        GL11.glTranslatef(-this.Side1A.offsetX, -this.Side1A.offsetY, -this.Side1A.offsetZ);
        GL11.glTranslatef(-this.Side1A.rotationPointX * f5, -this.Side1A.rotationPointY * f5, -this.Side1A.rotationPointZ * f5);
        this.Side1A.render(f5);
        GL11.glPopMatrix();
        GL11.glPushMatrix();
        GL11.glTranslatef(this.SonicBase8.offsetX, this.SonicBase8.offsetY, this.SonicBase8.offsetZ);
        GL11.glTranslatef(this.SonicBase8.rotationPointX * f5, this.SonicBase8.rotationPointY * f5, this.SonicBase8.rotationPointZ * f5);
        GL11.glScaled(1.0D, 0.5D, 1.0D);
        GL11.glTranslatef(-this.SonicBase8.offsetX, -this.SonicBase8.offsetY, -this.SonicBase8.offsetZ);
        GL11.glTranslatef(-this.SonicBase8.rotationPointX * f5, -this.SonicBase8.rotationPointY * f5, -this.SonicBase8.rotationPointZ * f5);
        this.SonicBase8.render(f5);
        GL11.glPopMatrix();
        GL11.glPushMatrix();
        GL11.glTranslatef(this.TopRod.offsetX, this.TopRod.offsetY, this.TopRod.offsetZ);
        GL11.glTranslatef(this.TopRod.rotationPointX * f5, this.TopRod.rotationPointY * f5, this.TopRod.rotationPointZ * f5);
        GL11.glScaled(0.8D, 1.0D, 0.8D);
        GL11.glTranslatef(-this.TopRod.offsetX, -this.TopRod.offsetY, -this.TopRod.offsetZ);
        GL11.glTranslatef(-this.TopRod.rotationPointX * f5, -this.TopRod.rotationPointY * f5, -this.TopRod.rotationPointZ * f5);
        this.TopRod.render(f5);
        GL11.glPopMatrix();
        GL11.glPushMatrix();
        GL11.glTranslatef(this.SonicBase3A.offsetX, this.SonicBase3A.offsetY, this.SonicBase3A.offsetZ);
        GL11.glTranslatef(this.SonicBase3A.rotationPointX * f5, this.SonicBase3A.rotationPointY * f5, this.SonicBase3A.rotationPointZ * f5);
        GL11.glScaled(1.3D, 0.7D, 1.3D);
        GL11.glTranslatef(-this.SonicBase3A.offsetX, -this.SonicBase3A.offsetY, -this.SonicBase3A.offsetZ);
        GL11.glTranslatef(-this.SonicBase3A.rotationPointX * f5, -this.SonicBase3A.rotationPointY * f5, -this.SonicBase3A.rotationPointZ * f5);
        this.SonicBase3A.render(f5);
        GL11.glPopMatrix();
        GL11.glPushMatrix();
        GL11.glTranslatef(this.SonicTop2.offsetX, this.SonicTop2.offsetY, this.SonicTop2.offsetZ);
        GL11.glTranslatef(this.SonicTop2.rotationPointX * f5, this.SonicTop2.rotationPointY * f5, this.SonicTop2.rotationPointZ * f5);
        GL11.glScaled(1.08D, 0.7D, 1.08D);
        GL11.glTranslatef(-this.SonicTop2.offsetX, -this.SonicTop2.offsetY, -this.SonicTop2.offsetZ);
        GL11.glTranslatef(-this.SonicTop2.rotationPointX * f5, -this.SonicTop2.rotationPointY * f5, -this.SonicTop2.rotationPointZ * f5);
        this.SonicTop2.render(f5);
        GL11.glPopMatrix();
        GL11.glPushMatrix();
        GL11.glTranslatef(this.SonicBase7.offsetX, this.SonicBase7.offsetY, this.SonicBase7.offsetZ);
        GL11.glTranslatef(this.SonicBase7.rotationPointX * f5, this.SonicBase7.rotationPointY * f5, this.SonicBase7.rotationPointZ * f5);
        GL11.glScaled(1.1D, 0.5D, 1.1D);
        GL11.glTranslatef(-this.SonicBase7.offsetX, -this.SonicBase7.offsetY, -this.SonicBase7.offsetZ);
        GL11.glTranslatef(-this.SonicBase7.rotationPointX * f5, -this.SonicBase7.rotationPointY * f5, -this.SonicBase7.rotationPointZ * f5);
        this.SonicBase7.render(f5);
        GL11.glPopMatrix();
        GL11.glPushMatrix();
        GL11.glTranslatef(this.Slider1.offsetX, this.Slider1.offsetY, this.Slider1.offsetZ);
        GL11.glTranslatef(this.Slider1.rotationPointX * f5, this.Slider1.rotationPointY * f5, this.Slider1.rotationPointZ * f5);
        GL11.glScaled(1.1D, 1.1D, 1.0D);
        GL11.glTranslatef(-this.Slider1.offsetX, -this.Slider1.offsetY, -this.Slider1.offsetZ);
        GL11.glTranslatef(-this.Slider1.rotationPointX * f5, -this.Slider1.rotationPointY * f5, -this.Slider1.rotationPointZ * f5);
        this.Slider1.render(f5);
        GL11.glPopMatrix();
        this.SonicCorner1.render(f5);
        GL11.glPushMatrix();
        GL11.glTranslatef(this.SonicBase8_1.offsetX, this.SonicBase8_1.offsetY, this.SonicBase8_1.offsetZ);
        GL11.glTranslatef(this.SonicBase8_1.rotationPointX * f5, this.SonicBase8_1.rotationPointY * f5, this.SonicBase8_1.rotationPointZ * f5);
        GL11.glScaled(1.1D, 1.0D, 1.1D);
        GL11.glTranslatef(-this.SonicBase8_1.offsetX, -this.SonicBase8_1.offsetY, -this.SonicBase8_1.offsetZ);
        GL11.glTranslatef(-this.SonicBase8_1.rotationPointX * f5, -this.SonicBase8_1.rotationPointY * f5, -this.SonicBase8_1.rotationPointZ * f5);
        this.SonicBase8_1.render(f5);
        GL11.glPopMatrix();
        GL11.glPushMatrix();
        GL11.glTranslatef(this.TopConnector.offsetX, this.TopConnector.offsetY, this.TopConnector.offsetZ);
        GL11.glTranslatef(this.TopConnector.rotationPointX * f5, this.TopConnector.rotationPointY * f5, this.TopConnector.rotationPointZ * f5);
        GL11.glScaled(1.4D, 1.0D, 1.4D);
        GL11.glTranslatef(-this.TopConnector.offsetX, -this.TopConnector.offsetY, -this.TopConnector.offsetZ);
        GL11.glTranslatef(-this.TopConnector.rotationPointX * f5, -this.TopConnector.rotationPointY * f5, -this.TopConnector.rotationPointZ * f5);
        this.TopConnector.render(f5);
        GL11.glPopMatrix();
        this.SonicBase2.render(f5);
        this.MiddleSonicBase.render(f5);
        GL11.glPushMatrix();
        GL11.glTranslatef(this.SideBar1.offsetX, this.SideBar1.offsetY, this.SideBar1.offsetZ);
        GL11.glTranslatef(this.SideBar1.rotationPointX * f5, this.SideBar1.rotationPointY * f5, this.SideBar1.rotationPointZ * f5);
        GL11.glScaled(0.1D, 0.8D, 0.5D);
        GL11.glTranslatef(-this.SideBar1.offsetX, -this.SideBar1.offsetY, -this.SideBar1.offsetZ);
        GL11.glTranslatef(-this.SideBar1.rotationPointX * f5, -this.SideBar1.rotationPointY * f5, -this.SideBar1.rotationPointZ * f5);
        this.SideBar1.render(f5);
        GL11.glPopMatrix();
    }

    /**
     * This is a helper function from Tabula to set the rotation of model parts
     */
    public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
        modelRenderer.rotateAngleX = x;
        modelRenderer.rotateAngleY = y;
        modelRenderer.rotateAngleZ = z;
    }
}
